[package]
name = "desktop"
version = "0.1.0"
edition = "2024"

[dependencies]
ironboy_core = {path = "../../crates/ironboy_core"}
sdl2 = { version = "0.37.0", features = ["image"] }
spin_sleep = "1.2.0"

