[package]
name = "ironboy_cpu"
version = "0.1.0"
edition = "2024"

[dependencies]
ironboy_common = {path = "../ironboy_common"}
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
